[package]
name = "nft-marketplace"
version = "1.0.0"
authors = []

[addresses]
marketplace="_"
owner="_"
treasury="_"

[dev-addresses]
marketplace="0a3eab45baea2c963e4def9a947c6d5a0cda5c6ec5c3034529a0a59040e87a81"
owner="30fe5a69e471a1af9cb12af811b77d004b8fc9f5cd363da515a645073fbe23a7"
treasury="ae3de3ab8cc615c9e77aa6085296f076e1bfae50f9c1b2702fb7e09f620f350d"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]
