[package]
name = "nft-marketplace"
version = "1.0.0"
authors = []

[addresses]
marketplace="_"
owner="_"
treasury="_"

[dev-addresses]
marketplace="3520b421d948b88fb9b2d87d323f888c0900f95787620dd1b3474077946a6682"
owner="30fe5a69e471a1af9cb12af811b77d004b8fc9f5cd363da515a645073fbe23a7"
treasury="ae3de3ab8cc615c9e77aa6085296f076e1bfae50f9c1b2702fb7e09f620f350d"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

[dev-dependencies]
